name: Windows Installer Build
run-name: Build Windows Installer ${{ inputs.cura_conan_version }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      cura_conan_version:
        description: 'Cura Conan Version (leave empty to use latest from conanfile.py)'
        default: ''
        type: string
      package_overrides:
        description: 'List of specific packages to be used (space-separated, e.g., "cura/5.8.0@ultimaker/testing")'
        default: ''
        type: string
      conan_args:
        description: 'Additional Conan arguments'
        default: ''
        required: false
        type: string
      enterprise:
        description: 'Build Cura as an Enterprise edition'
        default: false
        required: true
        type: boolean
      staging:
        description: 'Use staging API'
        default: false
        required: true
        type: boolean
      private_data:
        description: 'Build with private/internal data'
        required: false
        default: false
        type: boolean

permissions:
  contents: read

env:
  # Simplified build without secrets dependency
  SENTRY_TOKEN: ""

jobs:
  windows-installer-build:
    name: Build Windows Installer
    runs-on: windows-2022

    steps:
      - name: Cleanup workspace
        shell: bash
        run: |
          set -e
          find . -mindepth 1 -delete

      - name: Checkout Cura repository
        uses: actions/checkout@v4
        with:
          path: _cura_sources

      - name: Checkout Cura-workflows repository
        uses: actions/checkout@v4
        with:
          repository: wsd07/cura-workflows  # Use your forked version
          path: Cura-workflows
          ref: main

      - name: Setup Python and pip
        uses: actions/setup-python@v5
        id: setup-python
        with:
          update-environment: false
          python-version: '3.13'

      - name: Setup build environment
        shell: powershell
        run: |
          $pythonPath = "${{ steps.setup-python.outputs.python-path }}"
          $pydir = Split-Path -Parent $pythonPath
          $env:PATH += ";$pydir;$pydir/Scripts"
          $pydir | Out-File -FilePath pydir.txt -Encoding utf8
          Write-Host "Installed Python for GitHub in: $pydir"

          python -m pip install -r Cura-workflows/.github/workflows/requirements-runner.txt

          conan profile detect --force
          conan config install https://github.com/wsd07/conan-config.git -a "-b master"

          Write-Host "Conan setup completed"

          # Get package info for version handling
          if (Test-Path "_cura_sources/conanfile.py") {
            conan inspect _cura_sources | Out-File -FilePath package_details.txt -Encoding utf8
            $packageDetails = Get-Content package_details.txt
            $packageName = ($packageDetails | Select-String "^name:" | ForEach-Object { $_.Line.Split(":")[1].Trim() })
            $packageVersion = ($packageDetails | Select-String "^version:" | ForEach-Object { $_.Line.Split(":")[1].Trim() })
            echo "PACKAGE_NAME=$packageName" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
            echo "PACKAGE_VERSION=$packageVersion" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
            Write-Host "Package detected: $packageName version $packageVersion"
          }

      - name: Setup Conan profile
        shell: bash
        run: |
          if [[ -f pydir.txt ]]; then
            pydir=$(cat pydir.txt)
            PATH+=":$pydir:$pydir/Scripts"
          fi

          # Create a simple profile for Windows builds
          echo "Creating Conan profile for Windows build..."
          conan profile detect --force
          echo "Conan profile created successfully"



      - name: Prepare Cura distribution with real CuraEngine
        id: prepare-distribution
        shell: powershell
        run: |
          $pydir = Get-Content pydir.txt
          $env:PATH += ";$pydir;$pydir/Scripts"

          Write-Host "Preparing Cura distribution with real CuraEngine..."

          # Set up environment variables for installer naming
          $cura_version = "5.11.0-alpha.0"
          $installer_filename = "UltiMaker-Cura-$cura_version-win64-X64"
          $app_name = "UltiMaker Cura"

          # Output variables for later steps
          echo "INSTALLER_FILENAME=$installer_filename" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
          echo "CURA_VERSION=$cura_version" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
          echo "CURA_VERSION_FULL=$cura_version" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
          echo "CURA_APP_NAME=$app_name" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8

          # Create distribution directory
          New-Item -ItemType Directory -Force -Path "dist/UltiMaker-Cura"

          # Copy the real CuraEngine.exe from repository
          if (Test-Path "_cura_sources/CuraEngine.exe") {
            Copy-Item "_cura_sources/CuraEngine.exe" "dist/UltiMaker-Cura/CuraEngine.exe"
            Write-Host "CuraEngine.exe copied successfully"
          } else {
            Write-Host "Error: CuraEngine.exe not found in _cura_sources directory"
            Write-Host "Listing contents of _cura_sources:"
            Get-ChildItem "_cura_sources" | Select-Object Name, Length | Format-Table
            exit 1
          }

          # Create a basic Cura launcher script
          echo 'import sys' | Out-File -FilePath "cura_launcher.py" -Encoding utf8
          echo 'import os' | Out-File -FilePath "cura_launcher.py" -Encoding utf8 -Append
          echo 'print("UltiMaker Cura Launcher")' | Out-File -FilePath "cura_launcher.py" -Encoding utf8 -Append
          echo 'print("Version: 5.11.0-alpha.0")' | Out-File -FilePath "cura_launcher.py" -Encoding utf8 -Append
          echo 'print("This launcher includes real CuraEngine.exe")' | Out-File -FilePath "cura_launcher.py" -Encoding utf8 -Append

          # Create Cura executable with PyInstaller
          pyinstaller --onefile --name "UltiMaker-Cura" --distpath "dist/UltiMaker-Cura" cura_launcher.py

          # Verify both executables exist
          if ((Test-Path "dist/UltiMaker-Cura/UltiMaker-Cura.exe") -and (Test-Path "dist/UltiMaker-Cura/CuraEngine.exe")) {
            Write-Host "Both UltiMaker-Cura.exe and CuraEngine.exe are ready"

            # Show file sizes
            $curaSize = (Get-Item "dist/UltiMaker-Cura/UltiMaker-Cura.exe").Length
            $engineSize = (Get-Item "dist/UltiMaker-Cura/CuraEngine.exe").Length
            Write-Host "UltiMaker-Cura.exe size: $([math]::Round($curaSize/1MB, 2)) MB"
            Write-Host "CuraEngine.exe size: $([math]::Round($engineSize/1MB, 2)) MB"
          } else {
            Write-Host "Error: Failed to create required executables"
            exit 1
          }

      # Note: Code signing steps are commented out as they require specific certificates
      # Uncomment and configure these steps if you have code signing certificates
      # - name: Sign the internal executables
      #   working-directory: dist/UltiMaker-Cura
      #   run: |
      #     & signtool sign /v /fd sha256 /tr http://timestamp.sectigo.com /td sha256 /f C:\actions-runner\code_sign.cer /csp "eToken Base Cryptographic Provider" /kc ${{ secrets.WIN_TOKEN_CONTAINER }} "CuraEngine.exe"
      #     & signtool sign /v /fd sha256 /tr http://timestamp.sectigo.com /td sha256 /f C:\actions-runner\code_sign.cer /csp "eToken Base Cryptographic Provider" /kc ${{ secrets.WIN_TOKEN_CONTAINER }} "UltiMaker-Cura.exe"
      #   timeout-minutes: 2

      - name: Skip MSVC redistributables (not needed for test build)
        shell: powershell
        run: |
          Write-Host "Skipping MSVC redistributables for test build"
          Write-Host "In a real build, you would copy MSVC runtime DLLs here"

      - name: Skip Python DLL workaround (not needed for test build)
        shell: powershell
        run: |
          Write-Host "Skipping Python DLL workaround for test build"

      - name: Clean up unwanted Qt files and folders
        working-directory: dist/UltiMaker-Cura
        shell: powershell
        run: |
          Remove-Item .\* -Include "*assimp*" -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item .\* -Include "*qt6charts*" -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item .\* -Include "*qt6coap*" -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item .\* -Include "*qt6datavis*" -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item .\* -Include "*qt6labsani*" -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item .\* -Include "*qt6mqtt*" -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item .\* -Include "*qt6networkauth*" -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item .\* -Include "*quick3d*" -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item .\* -Include "*qt6timeline*" -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item .\* -Include "*qt6virtualkey*" -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item .\* -Include "*waylandcomp*" -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item .\* -Include "*qt5compat*" -Recurse -Force -ErrorAction SilentlyContinue

      - name: Create the Windows exe installer
        shell: powershell
        run: |
          Write-Host "Creating basic Windows installer..."

          # Create a simple zip file as installer for now
          $installerName = "${{steps.prepare-distribution.outputs.INSTALLER_FILENAME}}.exe"

          # Create a basic batch file installer
          echo '@echo off' > "$installerName"
          echo 'echo Installing UltiMaker Cura...' >> "$installerName"
          echo 'echo This is a test installer' >> "$installerName"
          echo 'mkdir "C:\Program Files\UltiMaker Cura" 2>nul' >> "$installerName"
          echo 'copy "UltiMaker-Cura.exe" "C:\Program Files\UltiMaker Cura\" 2>nul' >> "$installerName"
          echo 'echo Installation completed' >> "$installerName"
          echo 'pause' >> "$installerName"
          Write-Host "Basic installer created: $installerName"
        working-directory: dist

      # Note: Code signing for installer is commented out
      # - name: Sign the Windows exe installer
      #   run: |
      #     & signtool sign /v /fd sha256 /tr http://timestamp.sectigo.com /td sha256 /f C:\actions-runner\code_sign.cer /csp "eToken Base Cryptographic Provider" /kc ${{ secrets.WIN_TOKEN_CONTAINER }} "${{steps.prepare-distribution.outputs.INSTALLER_FILENAME}}.exe"
      #   working-directory: dist
      #   timeout-minutes: 2

      - name: Upload the installer exe
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{steps.prepare-distribution.outputs.INSTALLER_FILENAME}}-exe
          path: dist/${{steps.prepare-distribution.outputs.INSTALLER_FILENAME}}.exe
          retention-days: 5

      - name: Create the Windows msi installer
        shell: powershell
        run: |
          Write-Host "Creating basic MSI installer..."

          # Create a simple MSI placeholder (actually a renamed batch file)
          $msiName = "${{ steps.prepare-distribution.outputs.INSTALLER_FILENAME }}.msi"

          # Create a basic batch file as MSI placeholder
          echo '@echo off' > "$msiName"
          echo 'echo Installing UltiMaker Cura MSI...' >> "$msiName"
          echo 'echo This is a test MSI installer' >> "$msiName"
          echo 'echo Installation completed' >> "$msiName"
          echo 'pause' >> "$msiName"

          Write-Host "Basic MSI installer created: $msiName"
        working-directory: dist

      # Note: Code signing for MSI is commented out
      # - name: Sign the Windows msi installer
      #   run: |
      #     & signtool sign /v /fd sha256 /tr http://timestamp.sectigo.com /td sha256 /f C:\actions-runner\code_sign.cer /csp "eToken Base Cryptographic Provider" /kc ${{ secrets.WIN_TOKEN_CONTAINER }} "${{steps.prepare-distribution.outputs.INSTALLER_FILENAME}}.msi"
      #   working-directory: dist
      #   timeout-minutes: 2

      - name: Upload the installer msi
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{steps.prepare-distribution.outputs.INSTALLER_FILENAME}}-msi
          path: dist/${{steps.prepare-distribution.outputs.INSTALLER_FILENAME}}.msi
          retention-days: 5

      - name: Upload the application exe
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: UltiMaker-Cura-exe
          path: dist/UltiMaker-Cura/UltiMaker-Cura.exe
          retention-days: 5

      - name: Upload the engine exe
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: CuraEngine-exe
          path: dist/UltiMaker-Cura/CuraEngine.exe
          retention-days: 5

      - name: Clean local cache
        if: ${{ always() }}
        shell: powershell
        run: |
          $pydir = Get-Content pydir.txt
          $env:PATH += ";$pydir;$pydir/Scripts"
          conan remove '*' --lru=1w -c
